### ISSUE TITLE
Prevent swipe to dismiss

### ISSUE THREAD

**Issue by kjeremy** [ricnaaru/scrollable_bottom_sheet#2]
Is there a way to prevent the swipe to dismiss and stop at the minimum height?

**Comment by ricnaaru** [comment]
currently there isn't but i will add this to further milestone.. thanks for your suggestion

**Comment by ricnaaru** [comment]
I have fixed it, please try [0.0.3](https://pub.dartlang.org/packages/scrollable_bottom_sheet#-analysis-tab-) version

**Comment by kjeremy** [comment]
That seems to work once I set the `minimumHeight` though if I remove the
`initialHeight` it throws an error.

**Comment by ricnaaru** [comment]
Yes, it throws error because initialHeight is required and must not be null, can u explain to me what are you trying to achieve here?

**Comment by kjeremy** [comment]
I was playing around. It compiles without setting the `initialHeight` which is the case that I hit.

Ultimately my use case is to have a google map in the body with a bottom sheet that scrolls up like this one and the map resizes itself based on the bottomsheet.

**Comment by ricnaaru** [comment]
I see, ideally it's not minimum height what you're looking for, because it's always pinned at the bottom of scaffold, it's more like bottomNavigationBar or persistentFooterButton

I've tried with those, but still have something to figure out, since both bottomNavigationBar and persistentFooterButton are drawn below body by default in Flutter, so when I tried to showBottomSheet, the bottom sheet animation overlapped bottomNavigationBar or persistentFooterButton at Z-axis.

You can check my latest publish ([0.0.4](https://pub.dartlang.org/packages/scrollable_bottom_sheet#-analysis-tab-) also i spotted some bugs and fixed it)

Will notify you about the overlapping z-axis animation's update later

**Comment by ricnaaru** [comment]
Like I said earlier that ideally this would use bottomNavigationBar or persistentFooterButton, but since both of them are drawn below body of Scaffold, we cant use them.

So in my latest version in example/main.dart, i've create somewhat workaround to achieve google map bottom sheet imitation using Stack.. Please check the latest version [0.0.5](https://pub.dartlang.org/packages/scrollable_bottom_sheet)

Feel free to report to me any bug you find in the future.. thanks
