### ISSUE TITLE
Inconsistencies between this and Flutter Pub

### ISSUE THREAD

**Issue by kmccmk9** [ricnaaru/scrollable_bottom_sheet#6]
Just wanted to raise attention, that if users (like myself) come across this on Flutter Pub instead of GitHub, they are give a wildly different version number. This version 0.2.0 btw, does not work with any of the example or reference material. Switching the version back to 0.0.9 works fine.

**Comment by ricnaaru** [comment]
so you're saying 0.2.0 is not working for you? can you give your flutter doctor -v output for me? 

It might be my ascending changelog at [Dart Pub](https://pub.dartlang.org/packages/scrollable_bottom_sheet#-changelog-tab-), because 0.2.0 is supposed to be AndroidX upgrade, and if you're at Flutter 1.2.1, most probably this plugin won't work because i haven't upgrade to that version yet.

**Comment by jsroest** [comment]
Same here, example code does not work. In the pub/package version _ScrollableBottomSheetState is private, here in github, ScrollableBottomSheetState is public. It looks like the wrong branch or something is used to build the package.

**Comment by jsroest** [comment]
Oh, to be clear, the example that is in this github project, does work. If you copy the same code in a new project and reference the package, it will not work.

**Comment by ricnaaru** [comment]
I have updated README.md files on both example and plugin, please check it out and feel free to report new issue if you have one..
